import { ChatOpenAI } from "@langchain/openai";
import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import mongoose from "mongoose";

const productschema = new mongoose.Schema({
    title: String,
    description: String,
    price: Number,
    category: String,
    image: String,
});
const Product = mongoose.models.product || mongoose.model('product', productschema);

async function connectDB() {
    if (mongoose.connection.readyState >= 1) return;
    await mongoose.connect(process.env.MONGODB_URI);
}

async function run() {
    try {
        console.log("Connecting to database...");
        await connectDB();
        console.log("Connected.");
        
        const query = "footwear";
        console.log("User query:", query);
        
        const model = new ChatOpenAI({
          modelName: "gpt-4o-mini",
          temperature: 0.7,
          openAIApiKey: process.env.OPENAI_API_KEY,
        });

        const messages = [
          new SystemMessage("You are a helpful assistant that generates a short keyword based on the users query. The keyword should be relevant to the query and can be used to search for products in a database. Output ONLY a single word keyword, nothing else."),
          new HumanMessage("I am looking for a product that matches the following query: " + query)
        ];

        console.log("Invoking AI...");
        const aiRes = await model.invoke(messages);
        const keyword = aiRes.content.trim();
        console.log("Keyword generated by AI:", keyword);

        const products = await Product.find({
          $or: [
            { title: { $regex: keyword, $options: "i" } },
            { description: { $regex: keyword, $options: "i" } },
            { category: { $regex: keyword, $options: "i" } }
          ]
        });

        console.log("Found products:");
        console.log(JSON.stringify(products, null, 2));
    } catch (e) {
        console.error(e);
    } finally {
        process.exit(0);
    }
}
run();
